Delivered-To: ctgreybeard+mimetest@gmail.com
Received: by 10.194.242.5 with SMTP id wm5csp288165wjc;
        Sat, 6 Apr 2013 16:41:30 -0700 (PDT)
X-Received: by 10.66.220.10 with SMTP id ps10mr24034730pac.117.1365291689347;
        Sat, 06 Apr 2013 16:41:29 -0700 (PDT)
Return-Path: <ctgreybeard@me.com>
Received: from nk11p03mm-asmtp002.mac.com (nk11p03mm-asmtpout002.mac.com. [17.158.232.237])
        by mx.google.com with ESMTP id tr1si20282851pab.181.2013.04.06.16.41.28;
        Sat, 06 Apr 2013 16:41:29 -0700 (PDT)
Received-SPF: pass (google.com: domain of ctgreybeard@me.com designates 17.158.232.237 as permitted sender) client-ip=17.158.232.237;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of ctgreybeard@me.com designates 17.158.232.237 as permitted sender) smtp.mail=ctgreybeard@me.com;
       dmarc=pass (p=NONE dis=none) d=me.com
Received: from [192.168.2.101]
 (c-24-63-153-88.hsd1.ct.comcast.net [24.63.153.88])
 by nk11p03mm-asmtp002.mac.com
 (Oracle Communications Messaging Server 7u4-26.01(7.0.4.26.0) 64bit (built Jul
 13 2012)) with ESMTPSA id <0MKU00KU4XT1BT90@nk11p03mm-asmtp002.mac.com> for
 ctgreybeard+mimetest@gmail.com; Sat, 06 Apr 2013 23:41:27 +0000 (GMT)
X-Proofpoint-Virus-Version: vendor=fsecure
 engine=2.50.10432:5.10.8626,1.0.431,0.0.0000
 definitions=2013-04-06_08:2013-04-05,2013-04-06,1970-01-01 signatures=0
X-Proofpoint-Spam-Details: rule=notspam policy=default score=0 spamscore=0
 ipscore=0 suspectscore=0 phishscore=0 bulkscore=0 adultscore=0 classifier=spam
 adjust=0 reason=mlx scancount=1 engine=6.0.2-1302030000
 definitions=main-1304060312
From: ctgreybeard <ctgreybeard@me.com>
Content-type: multipart/alternative;
 boundary="Apple-Mail=_74918FA9-3CB8-4A33-A85D-BA0B756919D9"
Subject: Full test email
Message-id: <6C7D30F0-D71A-45D6-8F9C-0B78DED78132@me.com>
Date: Sat, 06 Apr 2013 19:41:25 -0400
To: "ctgreybeard+mimetest@gmail.com" <ctgreybeard+mimetest@gmail.com>
MIME-version: 1.0 (Mac OS X Mail 6.3 \(1503\))
X-Mailer: Apple Mail (2.1503)


--Apple-Mail=_74918FA9-3CB8-4A33-A85D-BA0B756919D9
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain;
	charset=windows-1252

Dear [% GivenName %],

This is a test message sent while we are testing the process for sending =
emails to the Greenwich High School Class of 1964.  We are in the midst =
of planning for the 50th reunion to be held in May 2014.  More to follow =
=85

Your email: [% Email %]

Your postal mailing address:
[% Addr1 %]
[% Addr2 %]
[% Addr3 %]
[% Addr4 %]

Thanks for listening!

GHS Reunion Committee=

--Apple-Mail=_74918FA9-3CB8-4A33-A85D-BA0B756919D9
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html;
	charset=windows-1252

<html><head><meta http-equiv=3D"Content-Type" content=3D"text/html =
charset=3Dwindows-1252"></head><body style=3D"word-wrap: break-word; =
-webkit-nbsp-mode: space; -webkit-line-break: after-white-space; ">Dear =
[% GivenName %],<div><br></div><div>This is a test message sent while we =
are testing the process for sending emails to the Greenwich High School =
Class of 1964. &nbsp;We are in the midst of planning for the 50th =
reunion to be held in May 2014. &nbsp;More to follow =
=85</div><div><br></div><div>Your email: [% Email =
%]</div><div><br></div><div>Your postal mailing address:</div><div>[% =
Addr1 %]</div><div>[% Addr2 %]</div><div>[% Addr3 %]</div><div>[% Addr4 =
%]</div><div><br></div><div>Thanks for =
listening!</div><div><br></div><div><i>GHS Reunion =
Committee</i></div></body></html>=

--Apple-Mail=_74918FA9-3CB8-4A33-A85D-BA0B756919D9--
