Delivered-To: ctgreybeard+mimetest@gmail.com
Received: by 10.194.242.5 with SMTP id wm5csp290376wjc;
        Sat, 6 Apr 2013 19:31:31 -0700 (PDT)
X-Received: by 10.66.157.195 with SMTP id wo3mr24462286pab.79.1365301890267;
        Sat, 06 Apr 2013 19:31:30 -0700 (PDT)
Return-Path: <ctgreybeard@me.com>
Received: from nk11p03mm-asmtp001.mac.com (nk11p03mm-asmtpout001.mac.com. [17.158.232.236])
        by mx.google.com with ESMTP id tf2si20839828pac.251.2013.04.06.19.31.29;
        Sat, 06 Apr 2013 19:31:30 -0700 (PDT)
Received-SPF: pass (google.com: domain of ctgreybeard@me.com designates 17.158.232.236 as permitted sender) client-ip=17.158.232.236;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of ctgreybeard@me.com designates 17.158.232.236 as permitted sender) smtp.mail=ctgreybeard@me.com;
       dmarc=pass (p=NONE dis=none) d=me.com
Received: from [192.168.2.101]
 (c-24-63-153-88.hsd1.ct.comcast.net [24.63.153.88])
 by nk11p03mm-asmtp001.mac.com
 (Oracle Communications Messaging Server 7u4-26.01(7.0.4.26.0) 64bit (built Jul
 13 2012)) with ESMTPSA id <0MKV00G4X5O9IWC0@nk11p03mm-asmtp001.mac.com> for
 ctgreybeard+mimetest@gmail.com; Sun, 07 Apr 2013 02:31:22 +0000 (GMT)
X-Proofpoint-Virus-Version: vendor=fsecure
 engine=2.50.10432:5.10.8626,1.0.431,0.0.0000
 definitions=2013-04-07_01:2013-04-05,2013-04-07,1970-01-01 signatures=0
X-Proofpoint-Spam-Details: rule=notspam policy=default score=0 spamscore=0
 ipscore=0 suspectscore=0 phishscore=0 bulkscore=0 adultscore=0 classifier=spam
 adjust=0 reason=mlx scancount=1 engine=6.0.2-1302030000
 definitions=main-1304060369
From: ctgreybeard <ctgreybeard@me.com>
Content-type: multipart/alternative;
 boundary="Apple-Mail=_0688E046-3ED4-431B-8A5B-500AF5E902E8"
Subject: Full Test email #2
Message-id: <D86BF1A2-98ED-405D-80A1-C1992AC32FC4@me.com>
Date: Sat, 06 Apr 2013 22:31:20 -0400
To: "ctgreybeard+mimetest@gmail.com" <ctgreybeard+mimetest@gmail.com>
MIME-version: 1.0 (Mac OS X Mail 6.3 \(1503\))
X-Mailer: Apple Mail (2.1503)


--Apple-Mail=_0688E046-3ED4-431B-8A5B-500AF5E902E8
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain;
	charset=windows-1252

Dear [% GivenName %],

This is a test message sent while we are testing the process for sending =
emails to the Greenwich High School Class of 1964.  We are in the midst =
of planning for the 50th reunion to be held in May 2014.  More to follow =
=85

Your email: [% Email %]

[% IF Addr2 -%]
We have your postal mailing address as:
[% Addr1 %]
[% Addr2 %]
[% Addr3 %]
[% Addr4 %]

If this is not correct then please let us know.
[% ELSE -%]
We don't have a postal mailing address for you. If we promise not to =
fill your mailbox with junk, and we do, could you please let us know =
what your postal mail address is? Thanks!
[% END %]

Thanks for listening!

GHS Reunion Committee=

--Apple-Mail=_0688E046-3ED4-431B-8A5B-500AF5E902E8
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html;
	charset=windows-1252

<html><head><meta http-equiv=3D"Content-Type" content=3D"text/html =
charset=3Dwindows-1252"></head><body style=3D"word-wrap: break-word; =
-webkit-nbsp-mode: space; -webkit-line-break: after-white-space; ">Dear =
[% GivenName %],<br><br>This is a test message sent while we are testing =
the process for sending emails to the Greenwich High&nbsp;School Class =
of 1964. &nbsp;We are in the midst of planning for the 50th reunion to =
be held in May 2014.&nbsp;&nbsp;More to follow =85<br><br>Your email: [% =
Email %]<div><br></div><div>[% IF Addr2 -%]</div><div>We have your =
postal mailing address as:<br>[% Addr1 %]<br>[% Addr2 %]<br>[% Addr3 =
%]<br>[% Addr4 %]</div><div><br></div><div>If this is not correct then =
please let us know.</div><div>[% ELSE -%]</div><div>We don't have a =
postal mailing address for you. If we promise not to fill your mailbox =
with junk, and we do, could you please let us know what your postal mail =
address is? Thanks!</div><div>[% END %]<br><br>Thanks for =
listening!<br><br><i>GHS Reunion Committee</i></div></body></html>=

--Apple-Mail=_0688E046-3ED4-431B-8A5B-500AF5E902E8--

