Delivered-To: ctgreybeard@gmail.com
Received: by 10.229.112.199 with SMTP id x7csp26901qcp;
        Fri, 11 Apr 2014 07:11:37 -0700 (PDT)
X-Received: by 10.69.31.235 with SMTP id kp11mr27826049pbd.33.1397225496859;
        Fri, 11 Apr 2014 07:11:36 -0700 (PDT)
Return-Path: <ctgreybeard@me.com>
Received: from nk11p03mm-asmtp001.mac.com (nk11p03mm-asmtpout001.mac.com. [17.158.232.236])
        by mx.google.com with ESMTP id z10si4336875pbx.138.2014.04.11.07.11.36
        for <ctgreybeard@gmail.com>;
        Fri, 11 Apr 2014 07:11:36 -0700 (PDT)
Received-SPF: pass (google.com: domain of ctgreybeard@me.com designates 17.158.232.236 as permitted sender) client-ip=17.158.232.236;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of ctgreybeard@me.com designates 17.158.232.236 as permitted sender) smtp.mail=ctgreybeard@me.com;
       dmarc=pass (p=NONE dis=NONE) header.from=me.com
MIME-version: 1.0
Content-transfer-encoding: 7BIT
Content-type: text/plain; CHARSET=US-ASCII
Received: from dads-macbook-pro.greybeard.org
 (c-67-189-220-94.hsd1.ct.comcast.net [67.189.220.94])
 by nk11p03mm-asmtp001.mac.com
 (Oracle Communications Messaging Server 7u4-27.08(7.0.4.27.7) 64bit (built Aug
 22 2013)) with ESMTPSA id <0N3V00L6GE251Q00@nk11p03mm-asmtp001.mac.com> for
 ctgreybeard@gmail.com; Fri, 11 Apr 2014 14:10:55 +0000 (GMT)
From: ctgreybeard <ctgreybeard@me.com>
Subject: Testing a message
Message-id: <BA397908-65E0-463B-B737-CC809EBF8C4C@me.com>
Date: Fri, 11 Apr 2014 10:10:52 -0400
To: Bill Waggoner <ctgreybeard@gmail.com>
X-Mailer: Apple Mail (2.1874)
X-MANTSH: 1TEIXREEbG1oaGkdHB0lGUkdDRl5PWBoaHhEKTEMXGx0EGx8SBBscHwQdGBAbHho
	fGhEKWE0XSxEKbX4XGhEKTFkXGxobGxEKWUkXEQpZXhdoY3kRCkNOF0sbGBpiTk1mHB0fZBl4c
	wcZaBseGxpeGREKWFwXGQQaBB0HTUsdEkhJHEwFGx0EGx8SBBscHwQdGBAbHhofGxEKXlkXYUx
	wU2ERCkNaFxwdBBsSEwQYGBoEEx4RCkJeFxsRCkJFF2NhWXhlGlMFaUITEQpCThdscGB5QB1iU
	mkaYhEKQkwXZUxtSx5HG2VsG2URCkJsF2xpTxMTU2BkfWYcEQpCQBd6HUtlHGFsT0ZmRREKQlg
	XYGtES2saHW17HEsRCnBnF2xyYWsZSxxZWVtoEQpwaBdmfkBrR0gTBUUcYBEKcGgXbn9QBQFGG
	UBGZF0RCnBsF2xua35vY2NmUGldEQpwTBdtWkdBAUVCZnh4ExE=
X-CLX-Spam: false
X-CLX-Score: 1011
X-Proofpoint-Virus-Version: vendor=fsecure
 engine=2.50.10432:5.11.96,1.0.14,0.0.0000
 definitions=2014-04-11_04:2014-04-11,2014-04-11,1970-01-01 signatures=0
X-Proofpoint-Spam-Details: rule=notspam policy=default score=0 spamscore=0
 suspectscore=2 phishscore=0 adultscore=0 bulkscore=0 classifier=spam adjust=0
 reason=mlx scancount=1 engine=7.0.1-1402240000 definitions=main-1404110227

This is a test. This is only a test. Had this been an actual message ...


Bill Waggoner
ctgreybeard@mac.com



