#!/sw/bin/zsh -f

# php gen.php >badges.html && wkhtmltopdf --print-media-type --page-size letter --margin-left 5mm --margin-right 5mm --margin-top 25mm --margin-bottom 26mm badges.html test3.pdf && open test3.pdf
php gen.php >badges.html && wkhtmltopdf --print-media-type --page-size letter --margin-left 0mm --margin-right 0mm --margin-top 26mm --margin-bottom 0mm badges.html test3.pdf && open test3.pdf
